apiVersion: v1
kind: Service
metadata:
  name: uber-ui
spec:
  selector:
    app: uber-ui
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-ui
spec:
  selector:
    matchLabels:
      app: uber-ui
  replicas: 2
  template:
    metadata:
      labels:
        app: uber-ui
    spec:
      containers:
      - name: uber-ui
        image: devopsthehardwayacr.azurecr.io/uberapp:v1
        ports:
        - containerPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uber-ui
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uber-ui
                port:
                  number: 80